services:
  # Nginx reverse proxy for dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "15433:15432"  # Different port for dev
    volumes:
      - "./logs/nginx-dev:/var/log/nginx:rw"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - api
    networks:
      - external
      - internal
    restart: unless-stopped
    environment:
      - ENV=development

  # API service for dev testing
  api:
    build:
      context: ./llm-api-service
      dockerfile: Dockerfile
    volumes:
      - "./llm-api-service/data-dev:/app/data:rw"
      - "./logs-dev:/app/logs:rw"
    networks:
      - internal
      - external
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - LOG_LEVEL=DEBUG
      - ENABLE_REQUEST_LOGGING=true
      - PRIVATE_MODE=false
      - COOKIE_FILE=/app/data/cookies.json
      - PROVIDER=You
      - REMOVE_SOURCES=true
      - DATABASE_PATH=/app/data/settings.db
      - ENV=development
    command: [
      "python", "-m", "freegpt4.FreeGPT4_Server",
      "--log-level", "DEBUG",
      "--cookie-file", "/app/data/cookies.json",
      "--provider", "You"
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/models"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      replicas: 1  # Single replica for dev
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true
