version: "3.9"
services:
  api:
    build: .
    user: www-data
    ports:
      - "15432:5500"
    volumes:
      - "./src/data:/app/src/data:rw"
      - "./logs:/app/logs:rw"
    networks:
      - "app_net"
    environment:
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/freegpt4.log
    command: --remove-sources --provider You --cookie-file /app/src/data/cookies.json --log-level INFO --log-file /app/logs/freegpt4.log --enable-request-logging

networks:
  app_net:
    external: true
