version: "3.9"
services:
  api:
    build: .
    user: www-data
    ports:
      - "15432:5500"
    volumes:
      - "./src/data:/app/src/data:rw"
      - "./logs:/app/logs:rw"
    networks:
      - "app_net"
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_FILE=/app/logs/freegpt4-dev.log
    command: --remove-sources --provider You --cookie-file /app/src/data/cookies.json --log-level DEBUG --log-file /app/logs/freegpt4-dev.log --enable-request-logging --enable-gui --password admin123

networks:
  app_net:
    external: true
