version: "3.9"
services:
  api:
    build: .
    user: www-data
    ports:
      - "15432:5500"
    volumes:
      - "./src/data:/app/src/data:rw"
      - "./logs:/app/logs:rw"
    networks:
      - "app_net"
    environment:
      - LOG_LEVEL=WARNING
      - LOG_FILE=/app/logs/freegpt4-prod.log
    command: --remove-sources --provider You --cookie-file /app/src/data/cookies.json --log-level WARNING --log-file /app/logs/freegpt4-prod.log --private-mode
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app_net:
    external: true
