name: Deploy to Production

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Debug trigger info
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Tag name: ${{ github.event.head_commit.message }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event ref: ${{ github.event.ref }}"
          echo "Event ref type: ${{ github.event.ref_type }}"
          echo "Event before: ${{ github.event.before }}"
          echo "Event after: ${{ github.event.after }}"
          echo "Event pusher: ${{ github.event.pusher.name }}"
          echo "Event repository: ${{ github.event.repository.full_name }}"
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
      
      - name: Setup Git credentials
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USERNAME }}"
          git config --local credential.helper store
          echo "https://${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
      
      - name: Setup SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PROD_HOST }} > ~/.ssh/known_hosts
      
      - name: Deploy to production server
        run: |
          # Подключение к серверу и выполнение деплоя
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.PROD_PORT }} ${{ secrets.PROD_USERNAME }}@${{ secrets.PROD_HOST }} << 'EOF'
            cd ${{ secrets.PROD_APP_PATH }}
            
            echo "=== Updating code ==="
            git checkout main
            git config --local user.email "${{ secrets.GIT_EMAIL }}"
            git config --local user.name "${{ secrets.GIT_USERNAME }}"
            git config --local credential.helper store
            echo "https://${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
            git pull origin main
            
            echo "=== Building Docker images ==="
            docker compose build --parallel --build-arg BUILDKIT_INLINE_CACHE=1
            
            echo "=== Starting cluster ==="
            chmod +x scripts/start-cluster.sh
            ./scripts/start-cluster.sh
            
            echo "=== Verifying deployment ==="
            docker compose ps
            echo "Checking data directory permissions:"
            ls -la llm-api-service/data/
            echo "Checking logs directory permissions:"
            ls -la logs/
            echo "Testing database write access:"
            touch llm-api-service/data/test_write && rm -f llm-api-service/data/test_write
            echo "Database write test successful"
            
            echo "=== Cleaning up old images ==="
            docker system prune -a -f
            
            echo "=== Production deployment completed successfully ==="
          EOF
